//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CLGeocoder;

@interface HoloGeocoder : NSObject
{
    CLGeocoder *_geocoder;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)requestAddressFromLatitude:(double)arg1 longitude:(double)arg2 requestId:(int)arg3 callback:(CDUnknownFunctionPointerType)arg4;
- (id)init;

@end

