//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class USSessionInfo;

@protocol UpsightSessionDelegate <NSObject>

@optional
- (void)upsightSessionDidResume;
- (void)upsightSessionWillResume:(USSessionInfo *)arg1;
- (void)upsightSessionDidStart;
- (void)upsightSessionWillStart:(USSessionInfo *)arg1;
@end

