//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, USActionMap;
@protocol USAction;

@protocol USActionFactoryInterface <NSObject>
- (id <USAction>)actionWithDictionary:(NSDictionary *)arg1 map:(USActionMap *)arg2;
@end

