//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "USActionMapDelegate-Protocol.h"
#import "USActionMapManagerInterface-Protocol.h"

@class NSMutableSet, NSString, USActionFactory;
@protocol USActionHandlerRegistry, UpsightDataStoreInterface;

@interface USActionMapManager : NSObject <USActionMapDelegate, USActionMapManagerInterface>
{
    USActionFactory *_actionsFactory;
    NSMutableSet *_actionMaps;
    NSMutableSet *_observers;
    id <UpsightDataStoreInterface> _dataStore;
}

@property(readonly, nonatomic) id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
- (void).cxx_destruct;
- (void)onDidCreateActionMap:(id)arg1;
@property(readonly, nonatomic) NSMutableSet *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) NSMutableSet *actionMaps; // @synthesize actionMaps=_actionMaps;
@property(readonly) USActionFactory *actionsFactory; // @synthesize actionsFactory=_actionsFactory;
- (void)actionMapDidFinishExecution:(id)arg1;
- (void)onDidStoreActionMap:(id)arg1 action:(unsigned long long)arg2;
@property(readonly) id <USActionHandlerRegistry> handlerRegistry;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)initWithDataStore:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

