//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "USContentUnit-Protocol.h"

@class NSString;

@interface USFuseContentUnit : NSObject <USContentUnit>
{
    NSString *_contentProvider;
    NSString *_zoneID;
}

@property(retain, nonatomic) NSString *zoneID; // @synthesize zoneID=_zoneID;
@property(readonly, nonatomic) NSString *contentProvider; // @synthesize contentProvider=_contentProvider;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

