//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface USHexEncoding : NSObject
{
}

+ (_Bool)isHexEncodedString:(id)arg1;
+ (id)dataForHexEncodedString:(id)arg1;
+ (id)hexEncodedStringForData:(id)arg1;

@end

