//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSNumber;

@interface USSessionInfo : NSObject
{
    NSNumber *_sessionNumber;
    double _sessionStartTime;
}

+ (id)getLatestSessionInfo;
+ (void)setUpsightSessionDelegate:(id)arg1;
@property(nonatomic) double sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
@property(retain, nonatomic) NSNumber *sessionNumber; // @synthesize sessionNumber=_sessionNumber;
- (void).cxx_destruct;
- (id)init;

@end

