//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSNumber, NSString, USSession;
@protocol USAnalyticsInterface, UpsightDataStoreInterface, UpsightSessionDelegate;

@interface USSessionManager : NSObject
{
    id <USAnalyticsInterface> _analytics;
    USSession *_currentSession;
    NSObject<UpsightSessionDelegate> *_sessionDelegate;
    id <UpsightDataStoreInterface> _dataStore;
    double _timeToNewSession;
    NSString *_currentState;
    NSDictionary *_stateTable;
    NSNumber *_messageID;
    NSNumber *_campaignID;
}

+ (void)startWithMessageID:(id)arg1 campaignID:(id)arg2;
+ (id)defaultConfiguration;
+ (id)sharedSessionManager;
@property(retain, nonatomic) NSNumber *campaignID; // @synthesize campaignID=_campaignID;
@property(retain, nonatomic) NSNumber *messageID; // @synthesize messageID=_messageID;
@property(retain, nonatomic) NSDictionary *stateTable; // @synthesize stateTable=_stateTable;
@property(nonatomic) NSString *currentState; // @synthesize currentState=_currentState;
@property(nonatomic) double timeToNewSession; // @synthesize timeToNewSession=_timeToNewSession;
@property(readonly, nonatomic) id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
@property(nonatomic) __weak NSObject<UpsightSessionDelegate> *sessionDelegate; // @synthesize sessionDelegate=_sessionDelegate;
@property(retain) USSession *currentSession; // @synthesize currentSession=_currentSession;
- (void).cxx_destruct;
- (void)set_sessionDelegate:(id)arg1;
- (void)saveSession:(id)arg1;
- (void)setMessageID:(id)arg1 campaignID:(id)arg2;
@property(readonly, nonatomic) id <USAnalyticsInterface> analytics; // @synthesize analytics=_analytics;
@property(readonly, copy, nonatomic) USSession *session;
- (void)applyConfiguration:(id)arg1;
- (void)sessionManagerConfigurationDidUpdate:(id)arg1 action:(unsigned long long)arg2;
- (void)checkForConfiguration;
- (id)exitPaused;
- (void)executePaused;
- (void)enterPaused;
- (id)exitResumed;
- (void)executeResumed;
- (void)enterResumed;
- (id)exitStarted;
- (void)executeStarted;
- (void)enterStarted;
- (id)exitLaunched;
- (void)executeLaunched;
- (void)endSession;
- (void)transition;
- (void)startWithMessageID:(id)arg1 campaignID:(id)arg2;
- (void)dealloc;
- (id)initWithDataStore:(id)arg1;
- (id)init;

@end

