//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface USStateDefinition : NSObject
{
    CDUnknownBlockType _enterBlock;
    CDUnknownBlockType _executeBlock;
    CDUnknownBlockType _exitBlock;
}

@property(copy, nonatomic) CDUnknownBlockType exitBlock; // @synthesize exitBlock=_exitBlock;
@property(copy, nonatomic) CDUnknownBlockType executeBlock; // @synthesize executeBlock=_executeBlock;
@property(copy, nonatomic) CDUnknownBlockType enterBlock; // @synthesize enterBlock=_enterBlock;
- (void).cxx_destruct;

@end

