//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol USViewController;

@protocol USViewControllerDelegate <NSObject>

@optional
- (void)contentUnitViewControllerDidDismiss:(id <USViewController>)arg1;
- (void)contentUnitViewControllerWillDismiss:(id <USViewController>)arg1;
@end

